### ISSUE TITLE
undefined method `match' for s(:send, nil, :sample_commit):Astrolabe::Node (NoMethodError)

### ISSUE THREAD

**Issue by connorshea** [tjgrathwell/rails5-spec-converter#2]
It crashes on [spec/requests/api/repositories_spec.rb](https://github.com/gitlabhq/gitlabhq/blob/6f8156cea587f08e11ad578bec012af103cc82e4/spec/requests/api/repositories_spec.rb) with the following:

```
/Users/connor/.rvm/gems/ruby-2.2.4/gems/rails5-spec-converter-1.0.3/lib/rails5/spec_converter/text_transformer.rb:54:in `block in looks_like_route_definition?': undefined method `match' for s(:send, nil, :sample_commit):Astrolabe::Node (NoMethodError)
	from /Users/connor/.rvm/gems/ruby-2.2.4/gems/rails5-spec-converter-1.0.3/lib/rails5/spec_converter/text_transformer.rb:50:in `each'
	from /Users/connor/.rvm/gems/ruby-2.2.4/gems/rails5-spec-converter-1.0.3/lib/rails5/spec_converter/text_transformer.rb:50:in `looks_like_route_definition?'
	from /Users/connor/.rvm/gems/ruby-2.2.4/gems/rails5-spec-converter-1.0.3/lib/rails5/spec_converter/text_transformer.rb:31:in `block in transform'
	from /Users/connor/.rvm/gems/ruby-2.2.4/gems/astrolabe-1.3.1/lib/astrolabe/node.rb:245:in `block in visit_descendants_with_types'
	from /Users/connor/.rvm/gems/ruby-2.2.4/gems/astrolabe-1.3.1/lib/astrolabe/node.rb:243:in `each'
	from /Users/connor/.rvm/gems/ruby-2.2.4/gems/astrolabe-1.3.1/lib/astrolabe/node.rb:243:in `visit_descendants_with_types'
	from /Users/connor/.rvm/gems/ruby-2.2.4/gems/astrolabe-1.3.1/lib/astrolabe/node.rb:246:in `block in visit_descendants_with_types'
	from /Users/connor/.rvm/gems/ruby-2.2.4/gems/astrolabe-1.3.1/lib/astrolabe/node.rb:243:in `each'
	from /Users/connor/.rvm/gems/ruby-2.2.4/gems/astrolabe-1.3.1/lib/astrolabe/node.rb:243:in `visit_descendants_with_types'
	from /Users/connor/.rvm/gems/ruby-2.2.4/gems/astrolabe-1.3.1/lib/astrolabe/node.rb:246:in `block in visit_descendants_with_types'
	from /Users/connor/.rvm/gems/ruby-2.2.4/gems/astrolabe-1.3.1/lib/astrolabe/node.rb:243:in `each'
	from /Users/connor/.rvm/gems/ruby-2.2.4/gems/astrolabe-1.3.1/lib/astrolabe/node.rb:243:in `visit_descendants_with_types'
	from /Users/connor/.rvm/gems/ruby-2.2.4/gems/astrolabe-1.3.1/lib/astrolabe/node.rb:246:in `block in visit_descendants_with_types'
	from /Users/connor/.rvm/gems/ruby-2.2.4/gems/astrolabe-1.3.1/lib/astrolabe/node.rb:243:in `each'
	from /Users/connor/.rvm/gems/ruby-2.2.4/gems/astrolabe-1.3.1/lib/astrolabe/node.rb:243:in `visit_descendants_with_types'
	from /Users/connor/.rvm/gems/ruby-2.2.4/gems/astrolabe-1.3.1/lib/astrolabe/node.rb:246:in `block in visit_descendants_with_types'
	from /Users/connor/.rvm/gems/ruby-2.2.4/gems/astrolabe-1.3.1/lib/astrolabe/node.rb:243:in `each'
	from /Users/connor/.rvm/gems/ruby-2.2.4/gems/astrolabe-1.3.1/lib/astrolabe/node.rb:243:in `visit_descendants_with_types'
	from /Users/connor/.rvm/gems/ruby-2.2.4/gems/astrolabe-1.3.1/lib/astrolabe/node.rb:246:in `block in visit_descendants_with_types'
	from /Users/connor/.rvm/gems/ruby-2.2.4/gems/astrolabe-1.3.1/lib/astrolabe/node.rb:243:in `each'
	from /Users/connor/.rvm/gems/ruby-2.2.4/gems/astrolabe-1.3.1/lib/astrolabe/node.rb:243:in `visit_descendants_with_types'
	from /Users/connor/.rvm/gems/ruby-2.2.4/gems/astrolabe-1.3.1/lib/astrolabe/node.rb:246:in `block in visit_descendants_with_types'
	from /Users/connor/.rvm/gems/ruby-2.2.4/gems/astrolabe-1.3.1/lib/astrolabe/node.rb:243:in `each'
	from /Users/connor/.rvm/gems/ruby-2.2.4/gems/astrolabe-1.3.1/lib/astrolabe/node.rb:243:in `visit_descendants_with_types'
	from /Users/connor/.rvm/gems/ruby-2.2.4/gems/astrolabe-1.3.1/lib/astrolabe/node.rb:226:in `each_node'
	from /Users/connor/.rvm/gems/ruby-2.2.4/gems/rails5-spec-converter-1.0.3/lib/rails5/spec_converter/text_transformer.rb:25:in `transform'
	from /Users/connor/.rvm/gems/ruby-2.2.4/gems/rails5-spec-converter-1.0.3/lib/rails5/spec_converter/cli.rb:9:in `block in run'
	from /Users/connor/.rvm/gems/ruby-2.2.4/gems/rails5-spec-converter-1.0.3/lib/rails5/spec_converter/cli.rb:7:in `glob'
	from /Users/connor/.rvm/gems/ruby-2.2.4/gems/rails5-spec-converter-1.0.3/lib/rails5/spec_converter/cli.rb:7:in `run'
	from /Users/connor/.rvm/gems/ruby-2.2.4/gems/rails5-spec-converter-1.0.3/exe/rails5-spec-converter:6:in `<top (required)>'
	from /Users/connor/.rvm/gems/ruby-2.2.4/bin/rails5-spec-converter:23:in `load'
	from /Users/connor/.rvm/gems/ruby-2.2.4/bin/rails5-spec-converter:23:in `<main>'
	from /Users/connor/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
	from /Users/connor/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by connorshea** [comment]
Fixed by 1.0.4
